steps:
  # ===== BACKEND =====
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/email-studio-backend:$SHORT_SHA
      - ./backend

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/email-studio-backend:$SHORT_SHA

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - email-studio-backend
      - --image
      - gcr.io/$PROJECT_ID/email-studio-backend:$SHORT_SHA
      - --platform
      - managed
      - --region
      - us-central1
      - --allow-unauthenticated
      - --port
      - "8080"
      - --memory
      - 512Mi
      - --cpu
      - "1"
      # Ejemplo de secrets (ajusta nombres reales en Secret Manager):
      # - --set-secrets
      # - OPENAI_API_KEY=OPENAI_API_KEY:latest,SFMC_CLIENT_ID=SFMC_CLIENT_ID:latest,SFMC_CLIENT_SECRET=SFMC_CLIENT_SECRET:latest

  # ===== FRONTEND (Docker + NGINX) =====
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/email-studio-frontend:$SHORT_SHA
      - --build-arg
      - VITE_API_BASE=$_FRONT_VITE_API_BASE
      - --build-arg
      - VITE_GCS_BUCKET=$_FRONT_VITE_GCS_BUCKET
      - --build-arg
      - VITE_GCS_PREFIX=$_FRONT_VITE_GCS_PREFIX
      - --build-arg
      - VITE_SFMC_CATEGORY_ID=$_FRONT_VITE_SFMC_CATEGORY_ID
      - ./frontend

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/email-studio-frontend:$SHORT_SHA

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - email-studio-frontend
      - --image
      - gcr.io/$PROJECT_ID/email-studio-frontend:$SHORT_SHA
      - --platform
      - managed
      - --region
      - us-central1
      - --allow-unauthenticated
      - --port
      - "8080"
      - --memory
      - 256Mi
      - --cpu
      - "1"

substitutions:
  # URL pública del backend (Cloud Run) vista por el frontend.
  # La primera vez puedes usar un placeholder y luego actualizarla
  # con la URL real de email-studio-backend.
  _FRONT_VITE_API_BASE: "https://EMAIL-STUDIO-BACKEND-URL.a.run.app"

  # Coherentes con backend/.env.example y frontend/.env.example
  _FRONT_VITE_GCS_BUCKET: "tu-bucket-imagenes"
  _FRONT_VITE_GCS_PREFIX: "dev"
  _FRONT_VITE_SFMC_CATEGORY_ID: "000000"

images:
  - "gcr.io/$PROJECT_ID/email-studio-backend:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/email-studio-frontend:$SHORT_SHA"
